engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  eslint:
    enabled: false
  nodesecurity:
    enabled: true
  ratings:
    paths:
      - "**/*.js"
exclude_paths:
- test/
- .gitattributes
- .gitignore
- .travis.yml
- CODE_OF_CONDUCT.md
- README.md
- LICENSE
- config.example.json
- .inch.json
- package-lock.json
- package.json
